name: Deploy Laravel Project on push

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the master branch

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3  # Checkout the repository code

      # - name: Copy .env
      #   run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # - name: Install Dependencies
      #   run: composer update --ignore-platform-reqs  # Install project dependencies

      - name: Copy .env 
        run: cp .env.example .env   # Copy .env file to folder

      - name: Install Dependencies   # Install project dependencies
        run: composer install --no-interaction --no-dev --optimize-autoloader      

      - name: Generate key
        run: php artisan key:generate  # Generate the application key

      - name: Generate storage link
        run: php artisan storage:link  # Create symbolic links for storage directories
        
      - name: Run database migrations
        run: php artisan migrate --force  # Run database migrations

      - name: Cache configuration
        run: php artisan config:cache  # Cache the configuration

      - name: Optimize application
        run: php artisan optimize  # Optimize the application

      - name: Directory Permissions
        run: chmod -R 775 storage bootstrap/cache 

      - name: Deploy to FTP Server 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3 # Deploy code to FTP Server

        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/shopez/
